// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYOq7NfDvZbldgSBkR1meXQrZrQNKd6Kk',
    appId: '1:783092117632:web:aba8232fb51bef4991b665',
    messagingSenderId: '783092117632',
    projectId: 'first-flutter-f083f',
    authDomain: 'first-flutter-f083f.firebaseapp.com',
    storageBucket: 'first-flutter-f083f.appspot.com',
    measurementId: 'G-PTPZP049JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeS0VggoxPEP2sBH05XYwTaeYfRRKGnCs',
    appId: '1:783092117632:android:3bb56af779470d9791b665',
    messagingSenderId: '783092117632',
    projectId: 'first-flutter-f083f',
    storageBucket: 'first-flutter-f083f.appspot.com',
  );
}
